import { PlantState } from '../../types/plant';
import { PHYSICS } from './constants';

export const generateInitialState = (): PlantState => ({
  clock: {
    tickCount: 0,
    gameTimeMinutes: 0,
    shiftPhase: 'normal',
  },
  core: {
    rodPosition: 48,
    neutronFlux: 100.0,
    thermalPower: PHYSICS.RATED_POWER_MWT,
    reactivity: 0,
    xenonConcentration: PHYSICS.XENON_EQUILIBRIUM,
    fuelTemperature: 304,
  },
  cooling: {
    rpvWaterLevel: 63,
    rpvPressure: 7.21,
    recircPumpSpeed: [100, 100],
    coreFlowRate: 100,
    drywellPressure: 1.2,
    suppressionPoolTemp: 25,
  },
  secondary: {
    turbineSpeed: 3600,
    turbineValvePosition: 100,
    feedwaterFlow: 1812,
    feedwaterPressure: 8.5,
    condenserPressure: 8.4,
    condenserVacuum: 98.0,
    mainSteamFlow: 1812,
    bypassValvePosition: 0,
  },
  flags: {
    msivOpen: true,
    bypassValveOpen: false,
    srvOpen: [false, false, false, false, false, false, false, false],
    adsActivated: false,
    rcicRunning: false,
    hpciRunning: false,
    lpciRunning: false,
    coreSprayRunning: false,
    recircPump: [true, true],
    feedwaterPump: [true, true],
    condensatePump: true,
    offSitePowerAvailable: true,
    dieselGeneratorRunning: false,
    batteryDcAvailable: true,
    batteryChargePercent: 100,
    scramSignalActive: false,
    rpsChannelFault: [false, false, false, false],
  },
  alarms: [],
  logs: [
    {
      tick: 0,
      gameTime: '00:00',
      message: 'SHIFT HANDOVER COMPLETE. UNIT 2 AT 100% POWER.',
      type: 'routine',
    },
  ],
  events: {
    activeEvents: [],
    eventPool: [], // populated later
    countdowns: [],
  },
  instruments: {
    rpvWaterLevel: { parameterId: 'rpvWaterLevel', failureMode: null, failedAtTick: null, displayValue: 63, trueValue: 63 },
    rpvPressure: { parameterId: 'rpvPressure', failureMode: null, failedAtTick: null, displayValue: 7.21, trueValue: 7.21 },
    neutronFlux: { parameterId: 'neutronFlux', failureMode: null, failedAtTick: null, displayValue: 100, trueValue: 100 },
    feedwaterFlow: { parameterId: 'feedwaterFlow', failureMode: null, failedAtTick: null, displayValue: 1812, trueValue: 1812 },
    drywellPressure: { parameterId: 'drywellPressure', failureMode: null, failedAtTick: null, displayValue: 1.2, trueValue: 1.2 },
    recircPumpSpeedA: { parameterId: 'recircPumpSpeedA', failureMode: null, failedAtTick: null, displayValue: 100, trueValue: 100 },
    recircPumpSpeedB: { parameterId: 'recircPumpSpeedB', failureMode: null, failedAtTick: null, displayValue: 100, trueValue: 100 },
  },
  equipment: {
    'FW-PUMP-A': { id: 'FW-PUMP-A', healthPercent: 100, degradationRate: 0.1, failureProbability: 0.01, breakerTripped: false, targetSetpoint: 1812, currentValue: 1812, ramping: false },
    'FW-PUMP-B': { id: 'FW-PUMP-B', healthPercent: 100, degradationRate: 0.1, failureProbability: 0.01, breakerTripped: false, targetSetpoint: 1812, currentValue: 1812, ramping: false },
    'RCIC': { id: 'RCIC', healthPercent: 100, degradationRate: 0.05, failureProbability: 0.01, breakerTripped: false, ramping: false },
    'HPCI': { id: 'HPCI', healthPercent: 100, degradationRate: 0.05, failureProbability: 0.01, breakerTripped: false, ramping: false },
    'RECIRC-A': { id: 'RECIRC-A', healthPercent: 100, degradationRate: 0.05, failureProbability: 0.01, breakerTripped: false, targetSetpoint: 100, currentValue: 100, ramping: false },
    'RECIRC-B': { id: 'RECIRC-B', healthPercent: 100, degradationRate: 0.05, failureProbability: 0.01, breakerTripped: false, targetSetpoint: 100, currentValue: 100, ramping: false },
  },
  difficulty: 'NORMAL',
  activeProcedure: undefined,
  pendingAroCommand: undefined,
});
